app-web:
  build: .
  ports:
    - "8080:8080"
  links:
    - app-db

app-db:
  build: ./src/main/resources/db
  expose:
    - "5432"
  volumes_from:
    - app-db-data

app-db-data:
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL'
  volumes:
    - /var/lib/postgresql/data